services:
  mysql:
    image: mysql:8.0
    container_name: simpmufy_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: simpmufy
      MYSQL_USER: simpmufy_user
      MYSQL_PASSWORD: simpmufy_pass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - simpmufy_net

  backend:
    build:
      context: ./apps/backend
    container_name: simpmufy_backend
    restart: always
    volumes:
      - ./apps/backend:/var/www
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=simpmufy
      - DB_USERNAME=simpmufy_user
      - DB_PASSWORD=simpmufy_pass
    depends_on:
      - mysql
    networks:
      - simpmufy_net

  frontend:
    build:
      context: ./apps/frontend
    container_name: simpmufy_frontend
    restart: always
    ports:
    - "3000:3000"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    networks:
      - simpmufy_net

  nginx:
    image: nginx:latest
    container_name: simpmufy_nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - simpmufy_net

volumes:
  db_data:

networks:
  simpmufy_net:
    driver: bridge
